#! /usr/bin/env python3
# ex: et sw=4 ts=4 sts=4

import sys
import re
import subprocess
import json
import multiprocessing as mp


class FileError(Exception):

    def __init__(self, node_path):
        self.node_path = node_path


class MissingError(FileError):

    def __str__(self):
        return 'error[missing]: {0}'.format(self.node_path)


class MetadataError(FileError):

    def __str__(self):
        return 'error[metadata]: {0}'.format(self.node_path)


def main(args=None):
    if args is None:
        args = sys.argv

    file_path = args[1]

    pool = mp.Pool()
    for r in pool.imap_unordered(speed, walk_nodes(file_path)):
        print(r)
        sys.stdout.flush()

    return 0


def walk_nodes(file_path):
    with open(file_path, 'r') as fin:
        for line in fin:
            m = re.match(r'^([\d\w]+)  (.*)$', line)
            local_hash = m.group(1)
            path = '/' + m.group(2)
            yield (path, local_hash)


def get_node_id(node_path):
    cmd = ['acdcli', 'resolve', '--', path]
    try:
        result = subprocess.check_output(cmd)
    except subprocess.CalledProcessError as e:
        raise MissingError(path)
    node_id = result.decode('utf-8').strip()
    return node_id


def get_node_hash(node_id):
    cmd = ['acdcli', 'metadata', '--', node_id]
    try:
        result = subprocess.check_output(cmd)
    except subprocess.CalledProcessError as e:
        raise MetadataError(path)
    metadata = json.loads(result.decode('utf-8'))
    remote_hash = metadata['contentProperties']['md5']
    return remote_hash


def speed(args):
    path, local_hash = args[0], args[1]

    try:
        node_id = get_node_id(path)
    except MissingError as e:
        return str(e)

    try:
        remote_hash = get_node_hash(node_id)
    except MetadataError as e:
        return str(e)

    if local_hash != remote_hash:
        return 'error[mismatch]:\n  path: {0}\n  expected: {1}\n  found: {2}'.format(path, local_hash, remove_hash)

    return 'ok: {0}'.format(path)


if __name__ == '__main__':
    exit_code = main()
    sys.exit(exit_code)
