#! /usr/bin/env python
#-*- coding: utf-8 -*-

import os, sys, re

def hasCommand( cmd ):
	if os.system( 'which ' + cmd + ' > /dev/null' ) != 0:
		raise SystemError( "One of commands: `" + cmd + "' not found." )

def getCommonPrefix( filePath ):
	filePattern = r'\d\d\d\d-\d\d-\d\d\s\d\d:\d\d:\d\d\s[\.\w]+\s+\d+\s+\d+\s\s(.*)'
	dirPattern = r'^\s+\d+\s+\d+\s+\d+ files, (\d+) folders.*$'

	pin = os.popen( '7z l "' + filePath + '"' )
	p = pin.read()
	pin.close()

	dirs = int( re.search( dirPattern, p, re.M ).group( 1 ) )
	if dirs == 0:
		return ''

	fileList = re.findall( filePattern, p )
	result = os.path.commonprefix( fileList )

	return result if result == fileList[-1] else ''

def getFileName( fileName ):
	return re.match( r'([^\.]*)(\..*)*', os.path.basename( fileName ) ).group( 1 )

def main( args = None ):
	if args is None:
		args = sys.argv

	hasCommand( '7z' )
	
	for f in args[1:]:
		if getCommonPrefix( f ) == '':
			os.system( '7z x "%s" -o"%s"' % ( f, getFileName( f ) ) )
		else:
			os.system( '7z x "%s"' % f )
	
	return 0

if __name__ == '__main__':
	sys.exit( main() )
