#! /usr/bin/env python
#-*- coding: utf-8 -*-

import os, sys, re

def hasCommand( cmd ):
	if os.system( 'which ' + cmd + ' > /dev/null' ) != 0:
		raise SystemError( "One of commands: `" + cmd + "' not found." )

def getFolderCount( filePath ):
	pin = os.popen( '7z l "%s" | tail -1' % filePath )
	out = pin.read()
	pin.close()

	result = re.search( r'(\d+)\s+files,\s+(\d+)\s+folders', out )
	if result is None:
		raise RuntimeError( 'What!?\n%s\n%s' % ( filePath, out ) )
	return int( result.group( 2 ) )

def main( args = None ):
	if args is None:
		args = sys.argv

	hasCommand( '7z' )
	
	for f in args[1:]:
		if getFolderCount( f ) != 1:
			os.system( '7z x "%s" -o"%s"' % ( f, os.path.splitext( os.path.basename( f ) )[0] ) )
		else:
			os.system( '7z x "%s"' % f )
	
	return 0

if __name__ == '__main__':
	sys.exit( main() )
