#! /usr/bin/env python3

import os
import os.path as op
import re
import sys

import yaml


def main(args=None):
    if args is None:
        args = sys.argv

    for root, folders, files in os.walk('.'):
        folders[:] = list(filter_by_patterns(root, folders, patterns, print))
        files[:] = list(filter_by_patterns(root, files, patterns, print))

    return 0


def load_patterns(input_stream):
    rv = yaml.safe_load(input_stream)
    return rv['exclude_pattern']


def filter_by_patterns(root, names, patterns, action):
    for name in names:
        if any(re.match(_, name, re.I) for _ in patterns):
            p = op.join(root, name)
            action(p)
        else:
            yield name


if __name__ == '__main__':
    sys.exit(main())
