#! /bin/sh

preview() {
	iconv -f $1 -t utf8 "$2" | pager
}

perform() {
	iconv -f $1 -t utf8 "$2" > "$2$3"
	if [ $? -eq 0 ] ; then
		mv "$2" "$2$4"
		mv "$2$3" "$2"
	fi
}

usage() {
	echo "Usage: `basename $0` -i <codec> [-p] files..."
	echo '\t-i codec:'
	echo '\t\tAssign input file codec.'
	echo '\t-p:'
	echo '\t\tPreview the result.'
}

action=perform

TMP=`getopt -o i:p -- "$@" 2>/dev/null`
if [ $? -ne 0 ] ; then
	echo >& 2 'Option error'
	usage
	exit 1
fi
eval set -- "$TMP"
while [ $1 != '--' ] ; do
	case "$1" in
	-i)
		from=$2
		shift
		;;
	-p)
		action=preview
		;;
	*)
		echo >&2 'unknown switch:' $1
		exit 1
		;;
	esac
	shift
done
shift

if [ $# -lt 1 ] ; then
	echo >&2 'need input file(s)'
	exit 1
fi

if [ -z $from ] ; then
	echo >&2 'what is the input codec?'
	exit 1
fi

for f in "$@" ; do
	$action $from "$f" '.utf8.tmp' '.backup'
done
