#! /bin/sh

preview() {
	iconv -f $1 -t utf8 "$2" | pager
}

perform() {
	iconv -f $1 -t utf8 "$2" > "$2$3"
	if [ $? -eq 0 ] ; then
		mv "$2" "$2$4"
		mv "$2$3" "$2"
	fi
}

action=perform

TMP=`getopt -o i:p -- "$@"`
eval set -- "$TMP"
while true ; do
	case "$1" in
	-i)
		from=$2
		shift 2
		;;
	-p)
		action=preview
		shift
		;;
	--)
		shift
		break
		;;
	*)
		echo >&2 'unknown switch:' $1
		exit 1
		;;
	esac
done

if [ -z $from ] ; then
	echo >&2 'what is the input codec?'
	exit 1
fi

for f in "$@" ; do
	$action $from "$f" '.utf8.tmp' '.backup'
done
