#! /usr/bin/env python

from __future__ import print_function
from __future__ import unicode_literals

import argparse
import sys
import zipfile


def main(args=None):
    if args is None:
        args = sys.argv

    parser = argparse.ArgumentParser()
    parser.add_argument('encoding', type=str, nargs=1)
    parser.add_argument('zip_file', type=str, nargs=1)
    parser.add_argument('destination', type=str, nargs='?')
    parser.add_argument('-l', '--list', action='store_true')
    args = parser.parse_args(args[1:])

    is_py3 = sys.version_info[0] >= 3

    with zipfile.ZipFile(args.zip_file[0]) as zin:
        for zi in zin.infolist():
            if is_py3:
                zi.filename = zi.filename.encode('cp437').decode(args.encoding[0])
            else:
                zi.filename = zi.filename.decode(args.encoding[0]).encode('utf-8')
            print(zi.filename)
            if not args.list:
                zin.extract(zi, args.destination)

    return 0


if __name__ == '__main__':
    exit_code = main()
    sys.exit(exit_code)
