#! /bin/bash

if [ $# -eq 1 ] ; then
	if [[ $1 =~ '\.tar\.gz$' ]] ; then
		exec tar -ztf $1 | less
	elif [[ $1 =~ '\.gz$' ]] ; then
		exec gzip -cd $1 | less
	else
		echo 'Invalid filename.' >&2
		exit 1
	fi
else
	echo 'Must takes one argument.' >&2
	exit 2
fi
