#! /usr/bin/env python3

import asyncio
import unicodedata
import sys

from wcpan.drive.core.drive import DriveFactory


async def main():
    factory = DriveFactory()
    factory.load_config()

    FORM = 'NFC'

    async with factory() as drive:
        root_node = await drive.get_root_node()
        async for root, folders, files in drive.walk(root_node):
            node_list = folders + files
            for child in node_list:
                if unicodedata.is_normalized(FORM, child.name):
                    continue
                new_name = unicodedata.normalize(FORM, child.name)
                print(child.id_)
                print(child.name)
                print(new_name)
                await drive.rename_node(child, new_parent=None, new_name=new_name)

    return 0


if __name__ == '__main__':
    sys.exit(asyncio.run(main()))
