services:
  dfd:
    build:
      target: production
      args:
        SQLITE_FILE: /mnt/data/dfd.sqlite
        PUBLIC_API_ORIGIN: ${DFD_API_ORIGIN}
    volumes:
      - ${DFD_DATA_DIR}:/mnt/data:rw
    ports:
      - "${DFD_HOST}:${DFD_PORT}:3000"
    environment:
      SQLITE_FILE: /mnt/data/dfd.sqlite
      PUBLIC_API_ORIGIN: ${DFD_API_ORIGIN}
      ORIGIN: ${DFD_API_ORIGIN}
    command: node build
