find_package(PkgConfig)

if(PKG_CONFIG_FOUND)
	pkg_check_modules(LR "libtorrent-rasterbar")
	if(LR_FOUND)
		set(LibtorrentRasterbar_FOUND ${LR_FOUND})
		set(LIBTORRENT_RASTERBAR_LIBRARIES ${LR_LIBRARIES})
		set(LIBTORRENT_RASTERBAR_LIBRARY_DIRS ${LR_LIBRARY_DIRS})
		set(LIBTORRENT_RASTERBAR_LDFLAGS ${LR_LDFLAGS})
		set(LIBTORRENT_RASTERBAR_LDFLAGS_OTHER ${LR_LDFLAGS_OTHER})
		set(LIBTORRENT_RASTERBAR_INCLUDE_DIRS ${LR_INCLUDE_DIRS})
		set(LIBTORRENT_RASTERBAR_CFLAGS ${LR_CFLAGS})
		set(LIBTORRENT_RASTERBAR_CFLAGS_OTHER ${LR_CFLAGS_OTHER})
	endif()
endif()

if(NOT LR_FOUND)
	# find by my hand
	find_path(LR_INCLUDE_DIRS libtorrent)
endif()

if(NOT LibtorrentRasterbar_FOUND)
	if(LibtorrentRasterbar_FIND_REQUIRED)
		message(FATAL_ERROR "Could NOT find libtorrent-rasterbar")
	endif()
endif()
