#! /bin/bash
# vim: ts=4 sts=4 sw=4 et
# ====
# debootstrap
# fakechroot
# fakeroot
# ====

# should move out
dpkg_tweek() {
    local path="$1"
    local full_name="$2"
    local email="$3"

	# add deb information
	cat >> "${path}/root/.bashrc" <<EOF

alias dquilt="quilt --quiltrc=\${HOME}/.quiltrc-dpkg"
export DEBFULLNAME="${full_name}"
export DEBEMAIL="${email}"
EOF
	cat >> "${path}/root/.quiltrc-dpkg" <<EOF
d=. ; while [ ! -d \$d/debian -a \`readlink -e \$d\` != / ]; do d=\$d/..; done
if [ -d \$d/debian ] && [ -z \$QUILT_PATCHES ]; then
    # if in Debian packaging tree with unset \$QUILT_PATCHES
    QUILT_PATCHES="debian/patches"
    QUILT_PATCH_OPTS="--reject-format=unified"
    QUILT_DIFF_ARGS="-p ab --no-timestamps --no-index --color=auto"
    QUILT_REFRESH_ARGS="-p ab --no-timestamps --no-index"
    QUILT_COLORS="diff_hdr=1;32:diff_add=1;34:diff_rem=1;31:diff_hunk=1;33:diff_ctx=35:diff_cctx=33"
    if ! [ -d \$d/debian/patches ]; then mkdir \$d/debian/patches; fi
fi
EOF
}

get_mirror() {
    local debian='http://ftp.jp.debian.org/debian/'
    local ubuntu='http://jp.archive.ubuntu.com/ubuntu/'

    case "$1" in
        stable|testing|unstable|sid)
            echo "$debian"
            ;;
        squeeze)
            echo "$debian"
            ;;
        wheezy)
            echo "$debian"
            ;;
        hardy|lucid|natty|oneiric|precise)
            echo "$ubuntu"
            ;;
        *)
            echo ""
            exit 1
            ;;
    esac
}

usage() {
    cat <<EOF
usage: $(basename $0) <options...> <sandbox_name>
    options:
        -a, --arch: i386 or amd64
        -b, --branch: distro branch
    sandbox_name: the sandbox name
EOF
}

SB_ROOT="${HOME}/.sandboxes"

# no root
if [ $(id -u) -eq 0 ] ; then
    echo 'no root'
    exit 1
fi

# make environment directory
if [ ! -d "${SB_ROOT}" ] ; then
    mkdir "${SB_ROOT}"
fi

tmp=$(getopt -o a:b: -l arch:,branch:,dpkg -n $(basename $0) -- "$@")
if [ $? -ne 0 ] ; then
    exit 1
fi
eval set -- "$tmp"

while true ; do
    case "$1" in
        -a|--arch)
            arch="$2"
            shift 2
            ;;
        -b|--branch)
            branch="$2"
            shift 2
            ;;
        --dpkg)
            dpkg='dpkg'
            shift 1
            ;;
        --)
            shift
            break
            ;;
        *)
            usage
            exit 1
    esac
done

if [ $# -ne 1 ] || [ -z "${arch}" ] || [ -z "${branch}" ] ; then
    usage
    exit 1
fi
mirror="$(get_mirror "${branch}")"
if [ $? -ne 0 ] ; then
    echo "unknown branch: ${branch}"
    exit 1
fi

name="$1"
path="${SB_ROOT}/${name}"

if [ -e "${path}" ] ; then
    echo "${name} exists"
    exit 1
fi

mkdir "${path}"
state_file="${path}/state"
path="${path}/environment"

fakeroot -s "${state_file}" fakechroot debootstrap --variant=fakechroot --arch="${arch}" "${branch}" "${path}" "${mirror}"

if [ -n ${dpkg} ] ; do
    dpkg_tweak "${path}" 'Wei Cheng Pan' 'legnaleurc@gmail.com'
done
