#! /bin/bash
# vim: ts=4 sts=4 sw=4 et
# ====
# chroot
# fakechroot
# fakeroot
# ====

usage() {
    echo "usage: $(basename $0) <sandbox_name>"
}

SB_ROOT="${HOME}/.sandboxes"

if [ ! -d "${SB_ROOT}" ] ; then
    echo "${SB_ROOT} does not exists"
    exit 1
fi

if [ $# -ne 1 ] ; then
    usage
    exit 1
fi

name="$1"
path="${SB_ROOT}/${name}"

if [ ! -d "${path}" ] ; then
    echo 'directory does not exists'
    exit 1
fi

state_file="${path}/state"
path="${path}/environment"

HOME="/root" TERM="$TERM" debian_chroot="${name}" fakeroot -i "${state_file}" -s "${state_file}" fakechroot chroot "${path}" "${SHELL}"
