version: "3"
services:
  migration:
    build:
      context: .
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./migration-data
        target: /root/data
      - type: bind
        source: ./config
        target: /root/.config
        read_only: true
      - ./:/root
