version: "3"
services:
  migration:
    build:
      context: .
    volumes:
      - type: bind
        source: .config
        target: /root/.config/wcpan.drive
        read_only: true
      - .migrate:/app/data
      - ./app:/app
