set number	"show line number
syntax on	"syntax color
set autoindent	"auto indent
"set smartindent "smart indent
"set cindent	"improved C/C++ indent
set ruler	"show the position of page
set showcmd	"show comand
filetype plugin indent on	"add plugin of indent
set nowrap	"stop auto wrap
colorscheme elflord	"color theme
set backspace=indent,eol,start	"where will backspace effect
set textwidth=0	"stop aotu warp
set hlsearch	"highlight keyword
set wrapscan	"back to top when search to bottom
"set cmdheight=2	"number of command line
set mouse=a	"active mouse support
set incsearch	"inproved search
set shiftwidth=8
set softtabstop=8
set tabstop=8
set noexpandtab
set termencoding=utf-8
if has("multi_byte")
	set encoding=utf-8
	setglobal fileencoding=utf-8
	set fileencoding=utf-8
	set fileencodings=utf-8,big5
else
	echoerr "Sorry, this version of (g)vim was not compiled with multi_byte"
endif
