name: drive CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  approval:
    name: Approval
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        id: approval
        uses: actions/github/request-reviews@v2
        with:
          reviewers: legnaleurc
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: |
          cd sandbox/typescript/drive
          npm install
          npm run build
