name: drive CI

on:
  push:
    branches:
      - master
    paths:
      - sandbox/typescript/drive

jobs:
  test:
    environment: Drive Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: |
          cd sandbox/typescript/drive
          npm install
          npm run build
